// <auto-generated />
using System;
using EFHomework.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFHomework.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250522175911_InitTable-PrescriptionMed")]
    partial class InitTablePrescriptionMed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFHomework.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDoctor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDoctor");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            IdDoctor = 1,
                            Email = "danov@gmail.com",
                            FirstName = "Daniel",
                            LastName = "Danov"
                        },
                        new
                        {
                            IdDoctor = 2,
                            Email = "gosho@gmail.com",
                            FirstName = "Gosho",
                            LastName = "Goshov"
                        },
                        new
                        {
                            IdDoctor = 3,
                            Email = "peshev@gmail.com",
                            FirstName = "Pesho",
                            LastName = "Peshev"
                        });
                });

            modelBuilder.Entity("EFHomework.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedicament"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMedicament");

                    b.ToTable("Medicament");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Description = "A non-steroidal anti-inflammatory drug (NSAID) used for pain relief and to reduce fever",
                            Name = "Ibuprofen",
                            Type = "Analgesic"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Description = "A pain reliever and fever reducer with no significant anti-inflammatory properties",
                            Name = "Paracetamol",
                            Type = "Analgesic"
                        },
                        new
                        {
                            IdMedicament = 3,
                            Description = "A β-lactam antibiotic used to treat a variety of bacterial infections",
                            Name = "Amoxicillin",
                            Type = "Antibiotic"
                        },
                        new
                        {
                            IdMedicament = 4,
                            Description = " An ACE inhibitor used to treat high blood pressure and heart failure",
                            Name = "Lisinopril",
                            Type = "Antihypertensive"
                        },
                        new
                        {
                            IdMedicament = 5,
                            Description = "A proton pump inhibitor used to treat acid reflux and stomach ulcers",
                            Name = "Omeprazole",
                            Type = "Gastroprotective"
                        },
                        new
                        {
                            IdMedicament = 6,
                            Description = "An oral medication used to control blood sugar levels in people with type 2 diabetes",
                            Name = "Metformin",
                            Type = "Antidiabetic"
                        });
                });

            modelBuilder.Entity("EFHomework.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPatient"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPatient");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            IdPatient = 1,
                            Birthdate = new DateOnly(1985, 5, 15),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            IdPatient = 2,
                            Birthdate = new DateOnly(1990, 8, 22),
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            IdPatient = 3,
                            Birthdate = new DateOnly(1975, 3, 10),
                            FirstName = "Michael",
                            LastName = "Brown"
                        },
                        new
                        {
                            IdPatient = 4,
                            Birthdate = new DateOnly(2000, 12, 5),
                            FirstName = "Emily",
                            LastName = "Johnson"
                        },
                        new
                        {
                            IdPatient = 5,
                            Birthdate = new DateOnly(1998, 7, 18),
                            FirstName = "David",
                            LastName = "Lee"
                        },
                        new
                        {
                            IdPatient = 6,
                            Birthdate = new DateOnly(1982, 1, 30),
                            FirstName = "Sophia",
                            LastName = "Martinez"
                        },
                        new
                        {
                            IdPatient = 7,
                            Birthdate = new DateOnly(1995, 4, 9),
                            FirstName = "Daniel",
                            LastName = "Garcia"
                        },
                        new
                        {
                            IdPatient = 8,
                            Birthdate = new DateOnly(1970, 9, 27),
                            FirstName = "Olivia",
                            LastName = "Lopez"
                        },
                        new
                        {
                            IdPatient = 9,
                            Birthdate = new DateOnly(1965, 6, 12),
                            FirstName = "William",
                            LastName = "Wilson"
                        },
                        new
                        {
                            IdPatient = 10,
                            Birthdate = new DateOnly(2002, 11, 2),
                            FirstName = "Emma",
                            LastName = "Anderson"
                        });
                });

            modelBuilder.Entity("EFHomework.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrescription"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("integer");

                    b.Property<int>("IdPatient")
                        .HasColumnType("integer");

                    b.HasKey("IdPrescription");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdPatient");

                    b.ToTable("Prescription");

                    b.HasData(
                        new
                        {
                            IdPrescription = 1,
                            Date = new DateOnly(2024, 5, 1),
                            DueDate = new DateOnly(2024, 5, 15),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 2,
                            Date = new DateOnly(2024, 5, 5),
                            DueDate = new DateOnly(2024, 5, 20),
                            IdDoctor = 2,
                            IdPatient = 2
                        },
                        new
                        {
                            IdPrescription = 3,
                            Date = new DateOnly(2024, 5, 10),
                            DueDate = new DateOnly(2024, 6, 10),
                            IdDoctor = 3,
                            IdPatient = 3
                        });
                });

            modelBuilder.Entity("EFHomework.Models.PrescriptionMedicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("integer");

                    b.Property<int>("IdPrescription")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Dose")
                        .HasColumnType("integer");

                    b.HasKey("IdMedicament", "IdPrescription");

                    b.HasIndex("IdPrescription");

                    b.ToTable("Prescription_Medicament");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            IdPrescription = 1,
                            Details = "Take one pill every 8 hours",
                            Dose = 200
                        },
                        new
                        {
                            IdMedicament = 2,
                            IdPrescription = 1,
                            Details = "As needed for fever",
                            Dose = 500
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 2,
                            Details = "Three times daily",
                            Dose = 250
                        },
                        new
                        {
                            IdMedicament = 6,
                            IdPrescription = 3,
                            Details = "Take with food",
                            Dose = 1000
                        },
                        new
                        {
                            IdMedicament = 5,
                            IdPrescription = 3,
                            Details = "Before breakfast",
                            Dose = 20
                        });
                });

            modelBuilder.Entity("EFHomework.Models.Prescription", b =>
                {
                    b.HasOne("EFHomework.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFHomework.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EFHomework.Models.PrescriptionMedicament", b =>
                {
                    b.HasOne("EFHomework.Models.Medicament", "Medicament")
                        .WithMany("PrescriptionMedicaments")
                        .HasForeignKey("IdMedicament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFHomework.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicaments")
                        .HasForeignKey("IdPrescription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicament");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("EFHomework.Models.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("EFHomework.Models.Medicament", b =>
                {
                    b.Navigation("PrescriptionMedicaments");
                });

            modelBuilder.Entity("EFHomework.Models.Patient", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("EFHomework.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionMedicaments");
                });
#pragma warning restore 612, 618
        }
    }
}
